// Main actions types
export const UPDATE_LOCATON_SUBMIT_STARTED = 'UPDATE_LOCATON_SUBMIT_STARTED'
export const UPDATE_LOCATON_SUBMIT_SUCESS  = 'UPDATE_LOCATON_SUBMIT_SUCESS'
export const UPDATE_LOCATON_SUBMIT_FAILED  = 'UPDATE_LOCATON_SUBMIT_FAILED'
export const UPDATE_LOCATON_SUBMIT_RELOAD  = 'UPDATE_LOCATON_SUBMIT_RELOAD'

export const UPDATE_ACTIVE_SUBMIT_STARTED = 'UPDATE_ACTIVE_SUBMIT_STARTED'
export const UPDATE_ACTIVE_SUBMIT_SUCESS  = 'UPDATE_ACTIVE_SUBMIT_SUCESS'
export const UPDATE_ACTIVE_SUBMIT_FAILED  = 'UPDATE_ACTIVE_SUBMIT_FAILED'
export const UPDATE_ACTIVE_SUBMIT_RELOAD  = 'UPDATE_ACTIVE_SUBMIT_RELOAD'
