//Auth actions types
export const REGISTER_SUBMIT_FAILED = 'REGISTER_SUBMIT_FAILED'
export const REGISTER_SUBMIT_SUCESS = 'REGISTER_SUBMIT_SUCESS'
export const REGISTER_SUBMIT_RELOAD = 'REGISTER_SUBMIT_RELOAD'
export const REGISTER_SUBMIT_STARTED = 'REGISTER_SUBMIT_STARTED'

// Main actions types
export const UPDATE_LOCATON_SUBMIT_STARTED = 'UPDATE_LOCATON_SUBMIT_STARTED'
export const UPDATE_LOCATON_SUBMIT_SUCESS  = 'UPDATE_LOCATON_SUBMIT_SUCESS'
export const UPDATE_LOCATON_SUBMIT_FAILED  = 'UPDATE_LOCATON_SUBMIT_FAILED'
export const UPDATE_LOCATON_SUBMIT_RELOAD  = 'UPDATE_LOCATON_SUBMIT_RELOAD'

export const UPDATE_ACTIVE_SUBMIT_STARTED = 'UPDATE_ACTIVE_SUBMIT_STARTED'
export const UPDATE_ACTIVE_SUBMIT_SUCESS  = 'UPDATE_ACTIVE_SUBMIT_SUCESS'
export const UPDATE_ACTIVE_SUBMIT_FAILED  = 'UPDATE_ACTIVE_SUBMIT_FAILED'
export const UPDATE_ACTIVE_SUBMIT_RELOAD  = 'UPDATE_ACTIVE_SUBMIT_RELOAD'

export const ACCEPT_ORDER_SUBMIT_FAILED  = 'ACCEPT_ORDER_SUBMIT_FAILED'
export const ACCEPT_ORDER_SUBMIT_SUCESS  = 'ACCEPT_ORDER_SUBMIT_SUCESS'
export const ACCEPT_ORDER_SUBMIT_RELOAD  = 'ACCEPT_ORDER_SUBMIT_RELOAD'
export const ACCEPT_ORDER_SUBMIT_STARTED  = 'ACCEPT_ORDER_SUBMIT_STARTED'

export const CANCEL_ORDER_FETCH_FAILED  = 'CANCEL_ORDER_FETCH_FAILED'
export const CANCEL_ORDER_FETCH_SUCESS  = 'CANCEL_ORDER_FETCH_SUCESS'
export const CANCEL_ORDER_FETCH_RELOAD  = 'CANCEL_ORDER_FETCH_RELOAD'
export const CANCEL_ORDER_FETCH_STARTED  = 'CANCEL_ORDER_FETCH_STARTED'

export const FETCH_POSTS='FETCH_POSTS'
export const NEW_POST = "NEW_POST";
export const GETSERVESIES = "GETSERVESIES";
export const REVERSE_GEOLOCATION="REVERSE_GEOLOCATION";
export const SETCOORDINATES="SETCOORDINATES";

export const COMPONENT_ENTER="COMPONENT_ENTER";
export const GETSELECTED_SERVICES="GETSELECTED_SERVICES";

export const GET_NOTIFICATIONS="GET_NOTIFICATIONS"
export const GET_COSTS="GET_COSTS"
export const TERMS="TERMS"
export const ABOUT_APP="ABOUT_APP"
