// Main actions types
export const UPDATE_LOCATON_SUBMIT_STARTED = 'UPDATE_LOCATON_SUBMIT_STARTED'
export const UPDATE_LOCATON_SUBMIT_SUCESS  = 'UPDATE_LOCATON_SUBMIT_SUCESS'
export const UPDATE_LOCATON_SUBMIT_FAILED  = 'UPDATE_LOCATON_SUBMIT_FAILED'
export const UPDATE_LOCATON_SUBMIT_RELOAD  = 'UPDATE_LOCATON_SUBMIT_RELOAD'

export const UPDATE_ACTIVE_SUBMIT_STARTED = 'UPDATE_ACTIVE_SUBMIT_STARTED'
export const UPDATE_ACTIVE_SUBMIT_SUCESS  = 'UPDATE_ACTIVE_SUBMIT_SUCESS'
export const UPDATE_ACTIVE_SUBMIT_FAILED  = 'UPDATE_ACTIVE_SUBMIT_FAILED'
export const UPDATE_ACTIVE_SUBMIT_RELOAD  = 'UPDATE_ACTIVE_SUBMIT_RELOAD'

export const FETCH_POSTS='FETCH_POSTS'
export const NEW_POST = "NEW_POST";
export const LOGIN = "LOGIN";
export const GETSERVESIES = "GETSERVESIES";
export const REVERSE_GEOLOCATION="REVERSE_GEOLOCATION";
export const SETCOORDINATES="SETCOORDINATES";

export const COMPONENT_ENTER="COMPONENT_ENTER";
export const GETSELECTED_SERVICES="GETSELECTED_SERVICES";

